basePath: /
host: localhost:1323
info:
  contact:
    email: code@fri3d.be
    name: code@fri3d.be
    url: http://www.swagger.io/support
  description: This is the Fri3d IRA ReST API
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://swagger.io/terms/
  title: Fri3d IRA API
  version: "1.0"
paths:
  /devices:
    get:
      consumes:
      - '*/*'
      description: get the keys for known devices.
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties: true
            type: object
      summary: get the keuys for known devices.
      tags:
      - root
schemes:
- http
swagger: "2.0"
